# Configures for nros building.

CC := gcc

INCLUDES := -I. -I../include

CFLAGS := $(INCLUDES) \
	-m32 -static -nostdinc -fno-builtin -ggdb -MD -O \
	-fno-strict-aliasing -fno-pic -fno-omit-frame-pointer \
	-fno-stack-protector -Wall

LD = ld

LDFLAGS = -m elf_i386
